import type {
  Service, Industry, Technology, CaseStudy,
  BlogPost, Testimonial, TeamMember, JobOpening, FAQ, Stat, NavItem,
} from '@/types'
import {
  Brain, Cloud, Code2, Globe, Smartphone, Shield, Settings, Repeat2,
  Database, Zap, Cpu, Lightbulb,
  Landmark, HeartPulse, Factory, ShoppingBag, GraduationCap, Truck,
  Building2, Building, RadioTower, Plane,
} from 'lucide-react'

export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Services', href: '/services',
    children: [
      { label: 'Artificial Intelligence', href: '/services/artificial-intelligence' },
      { label: 'Cloud Solutions',         href: '/services/cloud-solutions' },
      { label: 'Software Development',    href: '/services/software-development' },
      { label: 'Web Development',         href: '/services/web-development' },
      { label: 'Mobile Apps',             href: '/services/mobile-apps' },
      { label: 'Cybersecurity',           href: '/services/cybersecurity' },
      { label: 'Enterprise ERP',          href: '/services/enterprise-erp' },
      { label: 'DevOps',                  href: '/services/devops' },
      { label: 'Data Engineering',        href: '/services/data-engineering' },
      { label: 'UI/UX Design',            href: '/services/ui-ux-design' },
      { label: 'Business Automation',     href: '/services/business-automation' },
      { label: 'IT Consulting',           href: '/services/it-consulting' },
    ],
  },
  {
    label: 'Solutions', href: '/solutions',
    children: [
      { label: 'Digital Transformation', href: '/solutions' },
      { label: 'AI & Machine Learning',  href: '/solutions' },
      { label: 'Cloud Migration',        href: '/solutions' },
      { label: 'Enterprise Automation',  href: '/solutions' },
    ],
  },
  {
    label: 'Industries', href: '/industries',
    children: [
      { label: 'Banking & Finance',    href: '/industries' },
      { label: 'Healthcare',           href: '/industries' },
      { label: 'Manufacturing',        href: '/industries' },
      { label: 'Retail & E-Commerce',  href: '/industries' },
      { label: 'Education',            href: '/industries' },
      { label: 'Government',           href: '/industries' },
      { label: 'Logistics',            href: '/industries' },
      { label: 'Telecommunications',   href: '/industries' },
    ],
  },
  { label: 'Technologies', href: '/technologies' },
  { label: 'Case Studies', href: '/case-studies' },
  {
    label: 'Company', href: '/about',
    children: [
      { label: 'About Us',   href: '/about' },
      { label: 'Leadership', href: '/leadership' },
      { label: 'Clients',    href: '/clients' },
      { label: 'Blog',       href: '/blog' },
      { label: 'Careers',    href: '/careers' },
    ],
  },
  { label: 'Contact', href: '/contact' },
]

export const SERVICES: Service[] = [
  {
    slug: 'artificial-intelligence',
    title: 'Artificial Intelligence',
    shortDesc: 'Custom AI/ML models, LLM integration, and intelligent automation for enterprise workflows.',
    description: 'We design and deploy enterprise-grade AI systems that deliver measurable business outcomes. From custom machine learning models to large language model integrations, our AI solutions help organizations automate decisions, personalize experiences, and unlock value from unstructured data at scale.',
    icon: Brain,
    color: 'blue',
    features: ['Custom ML Model Development', 'LLM Integration & Fine-tuning', 'Computer Vision Systems', 'NLP & Text Analytics', 'Predictive Analytics', 'AI-Powered Automation'],
    benefits: ['Reduce manual effort by up to 70%', 'Accelerate decision-making with real-time insights', 'Improve customer experience through personalization', 'Unlock hidden value in your enterprise data'],
  },
  {
    slug: 'cloud-solutions',
    title: 'Cloud Solutions',
    shortDesc: 'AWS, Azure & GCP architecture, migration, and managed cloud services at enterprise scale.',
    description: 'Our cloud experts architect, migrate, and optimize enterprise workloads across AWS, Azure, and Google Cloud. We deliver multi-cloud strategies, cost optimization frameworks, and managed cloud operations that give your business the agility it needs to compete in the digital economy.',
    icon: Cloud,
    color: 'cyan',
    features: ['Cloud Architecture Design', 'Workload Migration', 'Multi-Cloud Strategy', 'FinOps & Cost Optimization', 'Managed Cloud Services', 'Cloud Security & Compliance'],
    benefits: ['Reduce infrastructure costs by 35-60%', 'Achieve 99.99% uptime SLAs', 'Scale on demand with zero downtime', 'Meet compliance requirements effortlessly'],
  },
  {
    slug: 'software-development',
    title: 'Software Development',
    shortDesc: 'Custom enterprise applications, APIs, and microservices built for performance and scale.',
    description: 'We build robust, scalable software solutions tailored to your enterprise requirements. Our engineering teams follow rigorous agile methodologies, clean architecture principles, and DevSecOps practices to deliver software that is maintainable, secure, and ready for the future.',
    icon: Code2,
    color: 'green',
    features: ['Custom Enterprise Applications', 'Microservices Architecture', 'RESTful & GraphQL APIs', 'Legacy System Modernization', 'Database Design & Optimization', 'Technical Architecture Review'],
    benefits: ['Faster time-to-market with agile sprints', 'Scalable architecture that grows with your business', 'Reduced technical debt through clean code practices', 'End-to-end ownership from design to deployment'],
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    shortDesc: 'High-performance web applications and portals using modern frameworks and best practices.',
    description: 'We craft exceptional web experiences using Next.js, React, and modern frontend technologies. From enterprise portals to consumer-facing platforms, our web solutions combine stunning design with rock-solid engineering to deliver experiences that convert and engage.',
    icon: Globe,
    color: 'purple',
    features: ['Enterprise Web Applications', 'Progressive Web Apps (PWA)', 'E-Commerce Platforms', 'Customer Portals', 'CMS Integration', 'Performance Optimization'],
    benefits: ['Core Web Vitals scores above 95', 'SEO-optimized architecture from day one', 'Accessibility compliant (WCAG 2.2 AA)', 'Sub-second page load times'],
  },
  {
    slug: 'mobile-apps',
    title: 'Mobile Apps',
    shortDesc: 'Native iOS & Android apps and cross-platform Flutter solutions with exceptional UX.',
    description: 'We build mobile applications that users love. Our mobile engineering teams specialize in native iOS and Android development as well as cross-platform solutions using Flutter and React Native, delivering pixel-perfect experiences with enterprise-grade security and performance.',
    icon: Smartphone,
    color: 'orange',
    features: ['Native iOS Development', 'Native Android Development', 'Cross-Platform (Flutter)', 'Mobile Backend (BaaS)', 'App Store Optimization', 'Mobile Security'],
    benefits: ['4.7+ average App Store rating', 'Offline-first architecture for reliability', 'Biometric authentication & enterprise security', 'Smooth 60fps animations and interactions'],
  },
  {
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    shortDesc: 'SOC, penetration testing, compliance frameworks, and zero-trust security architecture.',
    description: 'In an era of sophisticated cyber threats, we provide comprehensive security services that protect your most critical assets. From security operations center (SOC) setup to penetration testing and compliance management, our security experts keep your organization safe and audit-ready.',
    icon: Shield,
    color: 'red',
    features: ['Security Operations Center (SOC)', 'Penetration Testing & VAPT', 'Zero-Trust Architecture', 'Compliance (ISO 27001, SOC2, GDPR)', 'Incident Response', 'Security Awareness Training'],
    benefits: ['Reduce breach risk by up to 85%', 'Achieve compliance certifications faster', 'Real-time threat detection and response', '24x7 security monitoring and alerting'],
  },
  {
    slug: 'enterprise-erp',
    title: 'Enterprise ERP',
    shortDesc: 'SAP, Oracle, and custom ERP implementations that unify your business operations.',
    description: 'We implement and customize enterprise resource planning systems that bring your business operations together. Whether you need SAP, Oracle, Microsoft Dynamics, or a custom ERP solution, our consultants have the domain expertise to deliver implementations that drive operational excellence.',
    icon: Settings,
    color: 'teal',
    features: ['SAP Implementation & Support', 'Oracle ERP Cloud', 'Microsoft Dynamics 365', 'Custom ERP Development', 'ERP Integration & Data Migration', 'ERP Training & Change Management'],
    benefits: ['Eliminate data silos across departments', 'Real-time business visibility and reporting', 'Streamlined procurement and supply chain', 'Reduced operational costs through automation'],
  },
  {
    slug: 'devops',
    title: 'DevOps & SRE',
    shortDesc: 'CI/CD pipelines, Kubernetes orchestration, and infrastructure automation at scale.',
    description: 'We transform how your organization builds and delivers software. Our DevOps and SRE practice combines cultural transformation with powerful tooling to accelerate delivery velocity, improve reliability, and reduce the cost of change across your engineering organization.',
    icon: Repeat2,
    color: 'indigo',
    features: ['CI/CD Pipeline Design', 'Kubernetes & Container Orchestration', 'Infrastructure as Code (Terraform)', 'Monitoring & Observability', 'GitOps Implementation', 'SRE Best Practices'],
    benefits: ['Deploy up to 200x more frequently', 'Reduce deployment failures by 60%', 'Mean time to recovery (MTTR) under 1 hour', 'Infrastructure costs reduced by 40%'],
  },
  {
    slug: 'data-engineering',
    title: 'Data Engineering',
    shortDesc: 'Data lakes, pipelines, and real-time analytics platforms using Spark, Kafka, and dbt.',
    description: 'We build the data foundations that power modern AI and analytics initiatives. Our data engineering teams design and implement scalable data platforms — from ingestion and transformation pipelines to data lakes, warehouses, and real-time streaming architectures.',
    icon: Database,
    color: 'amber',
    features: ['Data Lake Architecture', 'Real-Time Streaming (Kafka)', 'Data Warehouse Design', 'ETL/ELT Pipelines', 'Data Quality & Governance', 'BI & Analytics Platforms'],
    benefits: ['Single source of truth for all business data', '10x faster analytics query performance', 'Real-time operational intelligence', 'GDPR and data privacy compliant'],
  },
  {
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    shortDesc: 'Research-driven design systems and interactive prototypes for enterprise products.',
    description: 'Great products start with great design. Our UX researchers and UI designers combine deep user empathy with business acumen to create interfaces that are beautiful, intuitive, and accessible. From design thinking workshops to production-ready design systems, we set your product up for success.',
    icon: Zap,
    color: 'violet',
    features: ['UX Research & User Testing', 'Information Architecture', 'Wireframing & Prototyping', 'Design System Creation', 'Accessibility Audits (WCAG 2.2)', 'Visual Design & Branding'],
    benefits: ['40% improvement in user task completion', 'Reduced support tickets through better UX', 'Consistent design language across all products', 'WCAG 2.2 AA accessibility compliance'],
  },
  {
    slug: 'business-automation',
    title: 'Business Automation',
    shortDesc: 'RPA, workflow orchestration, and intelligent process automation to eliminate repetitive work.',
    description: 'We help organizations automate repetitive, rule-based processes so their people can focus on higher-value work. Combining Robotic Process Automation (RPA) with AI-powered decision-making, we deliver automation solutions that reduce costs, eliminate errors, and accelerate throughput.',
    icon: Cpu,
    color: 'sky',
    features: ['Robotic Process Automation (RPA)', 'Intelligent Document Processing', 'Workflow Orchestration', 'BPM Platform Implementation', 'Process Mining & Discovery', 'AI-Enhanced Automation'],
    benefits: ['Reduce process costs by 60-80%', 'Eliminate human error from repetitive tasks', 'Process thousands of transactions per hour', 'ROI typically achieved within 6 months'],
  },
  {
    slug: 'it-consulting',
    title: 'IT Consulting',
    shortDesc: 'Strategic technology advisory, architecture reviews, and digital transformation roadmaps.',
    description: 'Our senior technology advisors partner with your leadership team to develop clear, actionable technology strategies. From digital transformation roadmaps to vendor selection and technology due diligence, we provide the strategic clarity you need to make confident technology investments.',
    icon: Lightbulb,
    color: 'green',
    features: ['Digital Transformation Strategy', 'Technology Architecture Review', 'Vendor Selection & Evaluation', 'IT Governance & Policy', 'Technology Due Diligence', 'CTO-as-a-Service'],
    benefits: ['Clear technology roadmap aligned to business goals', 'Avoid costly technology mistakes', 'Accelerate digital transformation initiatives', 'Build internal engineering capability'],
  },
]

export const INDUSTRIES: Industry[] = [
  { slug: 'banking-finance',    title: 'Banking & Finance',      icon: Landmark, color: '#1B4FD8', description: 'Fraud detection, digital banking, core banking modernization, and regulatory compliance technology for financial institutions.' },
  { slug: 'healthcare',         title: 'Healthcare',             icon: HeartPulse, color: '#10B981', description: 'Electronic health records, telemedicine platforms, AI diagnostics, and hospital management systems for healthcare providers.' },
  { slug: 'manufacturing',      title: 'Manufacturing',          icon: Factory, color: '#7C3AED', description: 'Smart factory IoT, predictive maintenance, supply chain optimization, and Industry 4.0 solutions for manufacturers.' },
  { slug: 'retail',             title: 'Retail & E-Commerce',    icon: ShoppingBag, color: '#F97316', description: 'Omnichannel commerce platforms, AI-powered personalization, inventory management, and loyalty solutions for retailers.' },
  { slug: 'education',          title: 'Education',              icon: GraduationCap, color: '#06B6D4', description: 'Learning management systems, EdTech platforms, adaptive learning AI, and campus management for educational institutions.' },
  { slug: 'logistics',          title: 'Logistics & Supply Chain', icon: Truck, color: '#EAB308', description: 'Real-time tracking, route optimization, warehouse management, and supply chain visibility for logistics companies.' },
  { slug: 'government',         title: 'Government & Public Sector', icon: Building2, color: '#0D9488', description: 'Citizen services portals, digital governance platforms, e-procurement, and public data analytics for government agencies.' },
  { slug: 'real-estate',        title: 'Real Estate',            icon: Building, color: '#EF4444', description: 'Property management platforms, virtual tours, CRM for real estate, and smart building management systems.' },
  { slug: 'telecommunications', title: 'Telecommunications',     icon: RadioTower, color: '#2563EB', description: 'BSS/OSS modernization, network analytics, customer experience platforms, and 5G enablement for telecom operators.' },
  { slug: 'travel',             title: 'Travel & Hospitality',   icon: Plane, color: '#8B5CF6', description: 'Booking engines, revenue management systems, loyalty platforms, and AI-powered travel experiences.' },
]

export const TECHNOLOGIES: Technology[] = [
  { name: 'Python',       category: 'Languages',    color: '#3776AB' },
  { name: 'TypeScript',   category: 'Languages',    color: '#3178C6' },
  { name: 'Java',         category: 'Languages',    color: '#007396' },
  { name: 'Go',           category: 'Languages',    color: '#00ADD8' },
  { name: 'Rust',         category: 'Languages',    color: '#DEA584' },
  { name: 'React',        category: 'Frontend',     color: '#61DAFB' },
  { name: 'Next.js',      category: 'Frontend',     color: '#000000' },
  { name: 'Angular',      category: 'Frontend',     color: '#DD0031' },
  { name: 'Vue.js',       category: 'Frontend',     color: '#4FC08D' },
  { name: 'Flutter',      category: 'Mobile',       color: '#54C5F8' },
  { name: 'React Native', category: 'Mobile',       color: '#61DAFB' },
  { name: 'Node.js',      category: 'Backend',      color: '#339933' },
  { name: 'FastAPI',      category: 'Backend',      color: '#009688' },
  { name: 'Spring Boot',  category: 'Backend',      color: '#6DB33F' },
  { name: 'AWS',          category: 'Cloud',        color: '#FF9900' },
  { name: 'Azure',        category: 'Cloud',        color: '#0078D4' },
  { name: 'Google Cloud', category: 'Cloud',        color: '#4285F4' },
  { name: 'Docker',       category: 'DevOps',       color: '#2496ED' },
  { name: 'Kubernetes',   category: 'DevOps',       color: '#326CE5' },
  { name: 'Terraform',    category: 'DevOps',       color: '#623CE4' },
  { name: 'TensorFlow',   category: 'AI/ML',        color: '#FF6F00' },
  { name: 'PyTorch',      category: 'AI/ML',        color: '#EE4C2C' },
  { name: 'OpenAI',       category: 'AI/ML',        color: '#10A37F' },
  { name: 'PostgreSQL',   category: 'Databases',    color: '#336791' },
  { name: 'MongoDB',      category: 'Databases',    color: '#47A248' },
  { name: 'Redis',        category: 'Databases',    color: '#DC382D' },
]

export const CASE_STUDIES: CaseStudy[] = [
  {
    slug: 'ai-fraud-detection-bank',
    title: 'AI Fraud Detection for Leading Private Bank',
    industry: 'Banking & Finance',
    challenge: 'A top-5 Indian private bank was losing ₹180 crore annually to payment fraud, with a legacy rule-based system generating 40% false positives that were damaging customer relationships.',
    solution: 'We built a real-time ML fraud detection engine using ensemble models (XGBoost + LSTM) processing 2M+ transactions daily with 2ms latency. The system learns continuously from new fraud patterns.',
    results: ['78% reduction in fraudulent transactions', 'False positive rate reduced from 40% to 3.2%', '₹140 crore saved in Year 1', '2ms average detection latency'],
    tech: ['Python', 'TensorFlow', 'Apache Kafka', 'AWS', 'PostgreSQL', 'Redis'],
    roi: '340% in 18 months',
    image: '/case-studies/banking.jpg',
  },
  {
    slug: 'hospital-digital-transformation',
    title: 'Hospital Network Digital Transformation',
    industry: 'Healthcare',
    challenge: 'A 500-bed hospital network across 8 cities was running on disconnected paper-based systems, leading to 3-hour average patient discharge times and poor care coordination.',
    solution: 'Implemented an integrated EHR, billing automation, patient engagement app, and clinical analytics platform across all facilities, with seamless data exchange between departments.',
    results: ['Patient discharge time reduced from 3 hours to 45 minutes', '94% patient satisfaction score', '₹8 crore annual operational savings', '100% paperless clinical workflow'],
    tech: ['React', 'Node.js', 'Azure', 'FHIR R4', 'PostgreSQL', 'Flutter'],
    roi: '220% in 24 months',
    image: '/case-studies/healthcare.jpg',
  },
  {
    slug: 'smart-factory-iot',
    title: 'Smart Factory IoT Platform for Steel Manufacturer',
    industry: 'Manufacturing',
    challenge: 'Unplanned equipment downtime was costing a major steel manufacturer ₹45 crore annually across 12 plants, with reactive maintenance creating production bottlenecks.',
    solution: 'Deployed 4,000+ IoT sensors across production lines, built an ML-powered predictive maintenance engine, and created a real-time operations dashboard for plant managers.',
    results: ['45% reduction in unplanned downtime', '₹22 crore annual maintenance savings', 'OEE improved from 71% to 92%', 'Predictive accuracy of 94% for failures'],
    tech: ['Python', 'Apache Kafka', 'AWS IoT', 'TensorFlow', 'InfluxDB', 'Grafana'],
    roi: '380% in 18 months',
    image: '/case-studies/manufacturing.jpg',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'generative-ai-enterprise-2025',
    title: 'How Generative AI is Reshaping Enterprise Operations in 2025',
    excerpt: 'From intelligent document processing to AI-powered code generation, discover how Indian enterprises are deploying generative AI to gain competitive advantage.',
    category: 'AI',
    author: 'Dr. Priya Sharma',
    date: '2025-06-15',
    readTime: '8 min read',
    image: '/blog/gen-ai.jpg',
  },
  {
    slug: 'multi-cloud-strategy-india',
    title: 'Building a Resilient Multi-Cloud Strategy for Indian Enterprises',
    excerpt: 'Why leading Indian companies are moving beyond single-cloud to architect resilient, cost-optimized multi-cloud environments across AWS, Azure, and GCP.',
    category: 'Cloud',
    author: 'Vikram Nair',
    date: '2025-06-08',
    readTime: '6 min read',
    image: '/blog/cloud.jpg',
  },
  {
    slug: 'zero-trust-security-2025',
    title: 'Zero Trust Architecture: The New Security Standard for 2025',
    excerpt: 'Traditional perimeter-based security is dead. Learn how to implement Zero Trust principles to protect your enterprise against modern cyber threats.',
    category: 'Cybersecurity',
    author: 'Arjun Mehta',
    date: '2025-05-28',
    readTime: '7 min read',
    image: '/blog/security.jpg',
  },
  {
    slug: 'platform-engineering-devops',
    title: 'Platform Engineering: The Evolution Beyond DevOps',
    excerpt: 'Platform engineering teams are revolutionizing developer productivity. Learn how to build internal developer platforms that 10x engineering throughput.',
    category: 'DevOps',
    author: 'Neha Kapoor',
    date: '2025-05-20',
    readTime: '9 min read',
    image: '/blog/devops.jpg',
  },
  {
    slug: 'nextjs-enterprise-patterns',
    title: 'Next.js 15 Enterprise Patterns for Scalable Web Applications',
    excerpt: 'Deep dive into advanced Next.js patterns including React Server Components, streaming, and edge deployment for building high-performance enterprise applications.',
    category: 'Software',
    author: 'Rohan Gupta',
    date: '2025-05-12',
    readTime: '10 min read',
    image: '/blog/nextjs.jpg',
  },
  {
    slug: 'design-systems-enterprise',
    title: 'Building Enterprise Design Systems That Scale Across 50+ Products',
    excerpt: 'How to architect and maintain a design system that serves multiple product teams, maintains consistency, and accelerates UI development by 40%.',
    category: 'UI/UX',
    author: 'Ananya Iyer',
    date: '2025-05-05',
    readTime: '7 min read',
    image: '/blog/design.jpg',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Rajesh Kumar',
    role: 'Chief Technology Officer',
    company: 'IndusFirst Bank',
    content: 'NexGen transformed our entire digital banking infrastructure in just 14 months. Their AI fraud detection alone saved us over ₹40 crore in the first year. Exceptional team, exceptional results — they are now our strategic technology partner of choice.',
    rating: 5,
    avatar: 'RK',
  },
  {
    name: 'Sarah Patterson',
    role: 'VP Engineering',
    company: 'TechCorp USA',
    content: 'We engaged NexGen for our multi-cloud migration across 3 data centers. They delivered on time, under budget, with zero downtime. Their DevOps team is world-class. We have since expanded the engagement to cover all our Asia-Pacific operations.',
    rating: 5,
    avatar: 'SP',
  },
  {
    name: 'Anand Mehta',
    role: 'Director of Operations',
    company: 'Bharat Steel Industries',
    content: 'Our 12 manufacturing plants now run on NexGen\'s IoT predictive maintenance platform. Downtime is down 45% and the ROI has been extraordinary — we recovered our investment in under 6 months. Truly a game-changing partnership.',
    rating: 5,
    avatar: 'AM',
  },
  {
    name: 'Dr. Meera Krishnan',
    role: 'CEO',
    company: 'MedCare Hospital Network',
    content: 'The digital transformation NexGen delivered across our 8 hospitals has been remarkable. Patient discharge times dropped from 3 hours to 45 minutes, and our staff satisfaction scores hit an all-time high. Technology finally serves our doctors, not the other way around.',
    rating: 5,
    avatar: 'MK',
  },
  {
    name: 'Faisal Al-Rashid',
    role: 'Group IT Director',
    company: 'Al-Rashid Retail Group, UAE',
    content: 'NexGen built our omnichannel commerce platform across 8 countries in 9 months. The platform now processes $2B in annual transactions with 99.99% uptime. Their team understood our Middle East market nuances — something other vendors could not offer.',
    rating: 5,
    avatar: 'FR',
  },
  {
    name: 'Priya Sundaram',
    role: 'CISO',
    company: 'FinServe Capital',
    content: 'After a near-miss security incident, we brought NexGen in to completely overhaul our security posture. Within 6 months, we had achieved ISO 27001 certification and SOC 2 Type II compliance. Their security team is outstanding — they think like adversaries.',
    rating: 5,
    avatar: 'PS',
  },
]

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: 'Suresh Venkataraman',
    role: 'Founder & CEO',
    bio: 'Former VP Engineering at Infosys with 22 years of enterprise technology leadership. Suresh founded NexGen with a vision to create an Indian IT company that combines global quality standards with deep local market expertise.',
    avatar: 'SV',
    linkedin: '#',
  },
  {
    name: 'Dr. Priya Sharma',
    role: 'Chief Technology Officer',
    bio: 'PhD in Computer Science from IIT Bombay, ex-Google AI Research. Dr. Sharma leads our AI and cloud architecture practice, with 18 patents in machine learning systems.',
    avatar: 'PS',
    linkedin: '#',
  },
  {
    name: 'Vikram Nair',
    role: 'Chief Business Officer',
    bio: '18 years in enterprise technology sales across India, USA, and the Middle East. Vikram has led partnerships with Fortune 500 companies and built our global client portfolio to 500+ enterprises.',
    avatar: 'VN',
    linkedin: '#',
  },
  {
    name: 'Ananya Iyer',
    role: 'VP Design & Experience',
    bio: 'Former Design Lead at Zoho and Freshworks, Ananya has shaped the user experience of products used by millions. She leads our UI/UX practice and internal design system.',
    avatar: 'AI',
    linkedin: '#',
  },
  {
    name: 'Arjun Mehta',
    role: 'VP Cybersecurity',
    bio: 'CISSP, CISM certified with 16 years in enterprise security. Former Head of Security at HDFC Bank. Arjun has built security programs for banks, hospitals, and government agencies across South Asia.',
    avatar: 'AM',
    linkedin: '#',
  },
  {
    name: 'Neha Kapoor',
    role: 'VP Cloud & DevOps',
    bio: 'AWS Solutions Architect Professional and Google Cloud Fellow. Neha leads our cloud practice and has overseen 200+ enterprise cloud migrations across all major platforms.',
    avatar: 'NK',
    linkedin: '#',
  },
]

export const JOB_OPENINGS: JobOpening[] = [
  {
    id: 'j1',
    title: 'Senior AI/ML Engineer',
    department: 'Artificial Intelligence',
    location: 'Bengaluru / Remote',
    type: 'Full-time',
    experience: '5+ years',
    description: 'Lead AI model development for enterprise clients. Design and deploy production ML systems at scale.',
  },
  {
    id: 'j2',
    title: 'Staff Software Engineer (Backend)',
    department: 'Engineering',
    location: 'Bengaluru / Hyderabad',
    type: 'Full-time',
    experience: '7+ years',
    description: 'Architect and build high-throughput microservices and distributed systems for Fortune 500 clients.',
  },
  {
    id: 'j3',
    title: 'Cloud Solutions Architect',
    department: 'Cloud',
    location: 'Bengaluru / Mumbai / Remote',
    type: 'Full-time',
    experience: '6+ years',
    description: 'Design and deliver multi-cloud architectures for enterprise clients across India and globally.',
  },
  {
    id: 'j4',
    title: 'Senior Frontend Engineer (React/Next.js)',
    department: 'Engineering',
    location: 'Bengaluru / Remote',
    type: 'Full-time',
    experience: '4+ years',
    description: 'Build world-class web applications and design systems for enterprise clients.',
  },
  {
    id: 'j5',
    title: 'Cybersecurity Analyst (VAPT)',
    department: 'Security',
    location: 'Bengaluru / Hyderabad',
    type: 'Full-time',
    experience: '3+ years',
    description: 'Conduct security assessments, penetration testing, and vulnerability management for clients.',
  },
  {
    id: 'j6',
    title: 'Product Designer (UI/UX)',
    department: 'Design',
    location: 'Bengaluru / Remote',
    type: 'Full-time',
    experience: '4+ years',
    description: 'Design exceptional digital experiences for enterprise web and mobile products.',
  },
]

export const HOME_STATS: Stat[] = [
  { value: '15', label: 'Years of Excellence', suffix: '+' },
  { value: '500', label: 'Enterprise Clients', suffix: '+' },
  { value: '1000', label: 'Projects Delivered', suffix: '+' },
  { value: '25', label: 'Countries Served', suffix: '+' },
  { value: '150', label: 'Technology Experts', suffix: '+' },
  { value: '99.9', label: 'Service Availability', suffix: '%' },
]

export const FAQS: FAQ[] = [
  {
    question: 'What makes NexGen different from other IT companies?',
    answer: 'NexGen combines the technical depth of a global systems integrator with the agility and client-centricity of a boutique consultancy. We maintain dedicated practice leads for each service area, ensuring you always work with genuine subject matter experts — not generalists.',
  },
  {
    question: 'How do you handle projects across different time zones?',
    answer: 'We operate a follow-the-sun model with offices in Bengaluru, Mumbai, Hyderabad, and Dubai. Our client engagement teams overlap with US, Europe, and APAC business hours, ensuring responsive communication and zero-delay project execution regardless of your location.',
  },
  {
    question: 'Do you work with startups or only enterprise clients?',
    answer: 'While our core practice serves mid-market and enterprise clients, we have a dedicated startup and growth-stage program that offers flexible engagement models. We have helped 50+ funded startups build their first products and scale their technology teams.',
  },
  {
    question: 'What certifications and quality standards do you maintain?',
    answer: 'NexGen holds ISO 27001 (Information Security), ISO 9001 (Quality Management), and CMMi Level 5 certifications. Our engineers carry AWS, Azure, GCP, and Kubernetes certifications, and our security team is CISSP and CISM certified.',
  },
  {
    question: 'How do you price your services?',
    answer: 'We offer flexible engagement models: Fixed-price projects for well-defined scope, Time & Materials for evolving requirements, and Dedicated Team models for long-term partnerships. All engagements start with a free consultation and detailed scoping session.',
  },
  {
    question: 'Can you take over and maintain systems built by other vendors?',
    answer: 'Absolutely. We have a specialized Legacy Modernization and Application Management practice. We conduct a comprehensive technical audit, stabilize the system, and then work with you on a modernization roadmap — or simply provide reliable ongoing support.',
  },
]

export const PROCESS_STEPS = [
  { step: '01', title: 'Discover', desc: 'Deep-dive workshops to understand your business goals, technical landscape, and success metrics.' },
  { step: '02', title: 'Research', desc: 'Competitive analysis, technical feasibility assessment, and stakeholder alignment sessions.' },
  { step: '03', title: 'Strategy', desc: 'Architecture decisions, technology selection, resource planning, and delivery roadmap creation.' },
  { step: '04', title: 'Design', desc: 'UX research, wireframing, prototyping, and design system development with stakeholder reviews.' },
  { step: '05', title: 'Develop', desc: 'Agile sprint-based development with daily standups, weekly demos, and continuous integration.' },
  { step: '06', title: 'Test', desc: 'Automated testing, performance benchmarking, security scanning, and UAT with your team.' },
  { step: '07', title: 'Deploy', desc: 'Zero-downtime deployments with blue-green strategies, rollback plans, and go-live support.' },
  { step: '08', title: 'Maintain', desc: '24x7 monitoring, proactive maintenance, SLA-backed support, and continuous improvement.' },
]
